[project]
name = "pyprep-chess"
version = "0.1.0"
description = "A simple chess sample project for experimenting with data-driven move selection."
authors = [{ name = "PyPrep" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
development = ["pytest>=7.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
